name: Cache Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dummy folder
        id: cache-step
        uses: actions/cache@v4
        with:
          path: .dummy-cache
          key: cache-b0399fa

      - name: Create dummy file
        run: echo "cached data" > .dummy-cache/data.txt

      - name: prime-cache-b0399fa
        id: prime-cache-b0399fa
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
